
### Create alert
GET http://localhost:8081/alerts

### Add matches to alert
GET http://localhost:8081/matches

### Add matches to alert
GET http://localhost:8081/dataset

### Create analsysis
GET http://localhost:8081/analysis

### Get recommendation
GET http://localhost:8081/recommendation